default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: personal_blog_development
  host: localhost

test:
  <<: *default
  database: personal_blog_test
  host: localhost

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB_PRODUCTION"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
  timeout: 5000
