default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
    <<: *default
    database: personal_blog_development

test:
    <<: *default
    database: personal_blog_test

production:
    <<: *default
    database: personal_blog_production
    username: personal_blog
    password: <%= ENV["PERSONAL_BLOG_DATABASE_PASSWORD"] %>
